paths:
  /category/{totalItems}:
    get:
      summary: Get a list of categories
      description: Retrieve a list of categories based on the totalItems parameter.
      parameters:
        - name: totalItems
          in: path
          required: true
          description: Number of categories to retrieve
          schema:
            type: integer
      responses:
        '200':
          description: OK. Returns the list of categories.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Category'
        '400':
          description: Bad Request. Invalid totalItems value.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /category/:
    get:
      summary: Get a list of categories
      description: Retrieve a list of categories based on a default value for the totalItems parameter.      
      responses:
        '200':
          description: OK. Returns the list of categories.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Category'
        '400':
          description: Bad Request. Invalid totalItems value.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    Category:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        title:
          type: string
        description:
          type: string
    ErrorResponse:
      type: object
      properties:
        error:
          type: string